-- Venta Taxi: новые функции
-- Выполни после базового venta_supabase_setup.sql

create table if not exists public.driver_applications (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  email text,
  car_info text not null,
  city text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.driver_applications enable row level security;
revoke all on table public.driver_applications from anon, authenticated;
grant select, insert, update on table public.driver_applications to authenticated;

drop policy if exists "Users can read own driver application" on public.driver_applications;
drop policy if exists "Users can create own driver application" on public.driver_applications;
drop policy if exists "Users can update own driver application" on public.driver_applications;
drop policy if exists "Admin can read all driver applications" on public.driver_applications;
drop policy if exists "Admin can update driver applications" on public.driver_applications;

create policy "Users can read own driver application"
on public.driver_applications for select to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create own driver application"
on public.driver_applications for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update own driver application"
on public.driver_applications for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Admin can read all driver applications"
on public.driver_applications for select to authenticated
using (lower(coalesce((select auth.jwt() ->> 'email'),'')) = lower('jony.oficcial@mail.ru'));

create policy "Admin can update driver applications"
on public.driver_applications for update to authenticated
using (lower(coalesce((select auth.jwt() ->> 'email'),'')) = lower('jony.oficcial@mail.ru'))
with check (true);

-- Сохранённые адреса пользователя
create table if not exists public.venta_saved_addresses (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  icon text not null default '📍',
  address text not null,
  created_at timestamptz not null default now()
);

alter table public.venta_saved_addresses enable row level security;
revoke all on table public.venta_saved_addresses from anon, authenticated;
grant select, insert, update, delete on table public.venta_saved_addresses to authenticated;

drop policy if exists "Users can manage own saved addresses" on public.venta_saved_addresses;
create policy "Users can manage own saved addresses"
on public.venta_saved_addresses for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Уведомления пользователя
create table if not exists public.venta_notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  body text not null,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.venta_notifications enable row level security;
revoke all on table public.venta_notifications from anon, authenticated;
grant select, insert, update, delete on table public.venta_notifications to authenticated;

drop policy if exists "Users can manage own notifications" on public.venta_notifications;
create policy "Users can manage own notifications"
on public.venta_notifications for all to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

-- Разрешённый список профилей без номера телефона, для разделения счёта
create or replace function public.venta_list_profiles()
returns table(id uuid, email text, first_name text, last_name text)
language sql
security definer
set search_path = public
as $$
  select vp.id, vp.email, vp.first_name, vp.last_name
  from public.venta_profiles vp
  where auth.uid() is not null
  order by coalesce(vp.first_name,''), coalesce(vp.last_name,'');
$$;

revoke all on function public.venta_list_profiles() from public;
grant execute on function public.venta_list_profiles() to authenticated;
